---
- name: Setup DeepScaler Environment on Lambda
  hosts: server
  remote_user: ubuntu
  vars:
    workspace_dir: /home/ubuntu
    python_version: "3.10"

  tasks:
    - name: Create dirs
      ansible.builtin.file:
        path: ~/.config
        state: directory

    - name: Create dirs
      ansible.builtin.file:
        path: ~/.config/git
        state: directory

    - name: Copy git
      ansible.posix.synchronize:
        src: ~/.config/git/config
        dest: ~/.config/git/config

    - name: Disable git gpg
      ansible.builtin.shell: |
        git config --global commit.gpgsign false
        git config --global tag.gpgsign false

    - name: Copy ssh config
      ansible.posix.synchronize:
        src: ~/.ssh/config
        dest: ~/.ssh/config

    - name: Copy github ssh key
      ansible.posix.synchronize:
        src: "{{ github_key }}"
        dest: "{{ github_key }}"

    - name: Copy repo
      ansible.posix.synchronize:
        src: "{{ repo_dir }}"
        dest: "{{ workspace_dir }}"
        rsync_opts:
          - --exclude=.venv
